name: Atualizar Respostas do Simulado

on:
  issues:
    types: [opened]

jobs:
  processar-respostas:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Instalar jq para manipular JSON
        run: sudo apt-get install jq

      - name: Adicionar nova resposta ao JSON
        run: |
          ISSUE_BODY=$(jq -r '.issue.body' $GITHUB_EVENT_PATH)
          
          # Criar o arquivo se não existir
          if [ ! -f respostas.json ]; then echo "[]" > respostas.json; fi
          
          # Adicionar a resposta ao JSON
          jq ". + [$ISSUE_BODY]" respostas.json > temp.json && mv temp.json respostas.json

      - name: Commit e push das mudanças
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add respostas.json
          git commit -m "Nova resposta adicionada"
          git push
